python models/eval/eval_seq2seq.py   \
		--nav_model_path /content/drive/MyDrive/mcr-agent/exp/MasterPolicy/latest.pth  \
		--pickup_model_path /content/drive/MyDrive/mcr-agent/exp/Interactions/PickupObject/latest.pth  \
		--put_model_path /content/drive/MyDrive/mcr-agent/exp/Interactions/PutObject/latest.pth  \
		--heat_model_path /content/drive/MyDrive/mcr-agent/exp/Interactions/HeatObject/latest.pth  \
		--cool_model_path /content/drive/MyDrive/mcr-agent/exp/Interactions/CoolObject/latest.pth  \
		--clean_model_path /content/drive/MyDrive/mcr-agent/exp/Interactions/CleanObject/latest.pth  \
		--toggle_model_path /content/drive/MyDrive/mcr-agent/exp/Interactions/ToggleObject/latest.pth  \
		--slice_model_path /content/drive/MyDrive/mcr-agent/exp/Interactions/SliceObject/latest.pth  \
		--object_model_path /content/drive/MyDrive/mcr-agent/exp/OEM/latest.pth  \
		--subgoal_model_path /content/drive/MyDrive/mcr-agent/exp/PCC/latest.pth  \
		--eval_split	valid_unseen                          \
		--huggingface_id		byeonghwikim/abp dataset       \
		--gpu                                               \
		--max_step	80                                 \
		--max_fail	10                                  \
		--num_threads 4;